// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Update_SuaHoaDon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_SuaHoaDon));
        
        string IMigrationMetadata.Id
        {
            get { return "202504301613316_Update_SuaHoaDon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
